# Generated by Django 5.0.6 on 2024-06-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
